version: '3.8'

services:
  nginx-proxy:
    build: .
    ports:
      - "80:80"
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: 2G
